"""Создал таблицы couriers, regions, working_hours

Revision ID: 0c1eeb4d8b79
Revises: 
Create Date: 2021-03-26 12:06:37.401668

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = '0c1eeb4d8b79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('courier_type', sa.String(length=20), nullable=True),
    sa.Column('orders_weight', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('courier_id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.courier_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('working_hours', models.TIMERANGE(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.courier_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('working_hours')
    op.drop_table('regions')
    op.drop_table('couriers')
    # ### end Alembic commands ###
