"""Создал таблицы orders, delivery_hours, couriers_orders

Revision ID: 6147db0e4343
Revises: 0c1eeb4d8b79
Create Date: 2021-03-26 12:08:40.555356

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = '6147db0e4343'
down_revision = '0c1eeb4d8b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('assign_time', sa.String(), nullable=True),
    sa.Column('complete_time', sa.String(), nullable=True),
    sa.Column('delivery_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('region', sa.Integer(), nullable=True),
    sa.Column('taken', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('delivery_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('delivery_hours', models.TIMERANGE(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_hours')
    op.drop_table('orders')
    op.drop_table('couriers_orders')
    # ### end Alembic commands ###
